import { StyleSheet } from 'react-native';
import { Palette } from './palette';
import { typography } from './typography';

export const createAuthStyles = (palette: Palette) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: palette.background,
    padding: 20,
    justifyContent: 'center',
  },
  card: {
    backgroundColor: palette.card,
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
  },
  iconWrapper: {
    alignItems: 'center',
    marginBottom: 16,
  },
  heading: {
    textAlign: 'center',
    color: palette.text,
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 4,
    fontFamily: typography.display,
  },
  subheading: {
    textAlign: 'center',
    color: palette.muted,
    fontSize: 14,
    marginBottom: 18,
    fontFamily: typography.body,
  },
  label: {
    color: palette.text,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 14,
    fontFamily: typography.body,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.overlay,
    borderRadius: 16,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: palette.overlayBorder,
  },
  inputContainerFocused: {
    borderColor: '#4A8CFF',
    shadowColor: '#4A8CFF',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
  },
  textInput: {
    flex: 1,
    color: palette.text,
    paddingVertical: 14,
    fontFamily: typography.body,
  },
  helperRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  forgot: {
    color: palette.primary,
    fontWeight: '700',
    fontFamily: typography.body,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    gap: 8,
  },
  checkboxBox: {
    width: 18,
    height: 18,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  termsText: {
    color: palette.muted,
    flex: 1,
    flexWrap: 'wrap',
    fontFamily: typography.body,
  },
  link: {
    color: palette.primary,
    fontWeight: '700',
  },
  primaryButton: {
    marginTop: 20,
    backgroundColor: palette.primary,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: palette.text,
    fontWeight: '800',
    fontSize: 16,
    fontFamily: typography.display,
  },
  oauthSeparator: {
    marginVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
    position: 'relative',
    alignItems: 'center',
  },
  oauthSeparatorText: {
    position: 'absolute',
    top: -10,
    paddingHorizontal: 8,
    backgroundColor: palette.card,
    color: palette.muted,
    fontFamily: typography.body,
  },
  oauthButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.card,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: palette.overlayBorder,
    marginTop: 12,
    gap: 10,
  },
  appleButton: {
    width: '100%',
    height: 48,
    marginTop: 12,
  },
  oauthText: {
    color: palette.text,
    fontWeight: '700',
    fontFamily: typography.body,
  },
  footerText: {
    textAlign: 'center',
    color: palette.muted,
    marginTop: 18,
    fontFamily: typography.body,
  },
  footerLink: {
    color: palette.primary,
    fontWeight: '700',
    fontFamily: typography.body,
  },
  errorText: {
    color: '#ff6b6b',
    marginTop: 8,
  },
});
