import { Dimensions, StyleSheet } from 'react-native';
import { Palette } from '../../theme/palette';
import { typography } from '../../theme/typography';

const { width } = Dimensions.get('window');

export const createOnboardingStyles = (palette: Palette) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  brandBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(90,239,213,0.16)',
  },
  brandBadgeText: {
    color: palette.success,
    fontWeight: '700',
    letterSpacing: 0.4,
    fontSize: 11,
    textTransform: 'uppercase',
  },
  brandTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '800',
    fontFamily: typography.display,
    letterSpacing: 0.2,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  skip: {
    color: palette.primary,
    fontWeight: '700',
  },
  listContent: {
    paddingHorizontal: 6,
  },
  slideWrapper: {
    width,
    paddingHorizontal: 12,
  },
  card: {
    flex: 1,
    height: 520,
    borderRadius: 28,
    padding: 28,
    justifyContent: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    overflow: 'hidden',
  },
  cardSheen: {
    position: 'absolute',
    top: -60,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  cardGlow: {
    position: 'absolute',
    bottom: -80,
    left: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(90,239,213,0.08)',
  },
  iconCircle: {
    width: 58,
    height: 58,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(74, 140, 255, 0.16)',
    color: palette.success,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    fontWeight: '700',
  },
  badgePill: {
    marginTop: 'auto',
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
  },
  badgePillText: {
    fontWeight: '700',
  },
  title: {
    color: palette.text,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 14,
    fontFamily: typography.display,
  },
  subtitle: {
    color: palette.muted,
    fontSize: 16,
    lineHeight: 22,
    fontFamily: typography.body,
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginTop: 24,
    marginBottom: 20,
  },
  dot: {
    height: 12,
    borderRadius: 8,
  },
  primaryButton: {
    backgroundColor: palette.primary,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    shadowColor: palette.primary,
    shadowOpacity: 0.25,
    shadowRadius: 12,
  },
  primaryButtonText: {
    color: palette.text,
    fontWeight: '800',
    fontSize: 16,
    letterSpacing: 0.3,
    fontFamily: typography.display,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    paddingVertical: 14,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  secondaryButtonText: {
    color: palette.text,
    fontWeight: '700',
    fontSize: 14,
    fontFamily: typography.body,
  },
  mainCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 24,
    backgroundColor: palette.card,
    padding: 24,
    borderWidth: 1,
    borderColor: palette.overlayBorder,
    alignSelf: 'center',
    marginTop: 80,
  },
});
