import { Dimensions, StyleSheet } from 'react-native';
import { Palette } from '../../theme/palette';
import { typography } from '../../theme/typography';

const { width, height } = Dimensions.get('window');
const screenHorizontalPadding = 18;
const slideWidth = width - screenHorizontalPadding * 2;
const cardHeight = Math.min(528, Math.max(484, height * 0.615));
const previewHeight = Math.min(236, Math.max(198, height * 0.265));

export const createOnboardingStyles = (palette: Palette) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
    paddingHorizontal: 18,
    paddingTop: 8,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  brandBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(90,239,213,0.16)',
  },
  brandBadgeText: {
    color: palette.success,
    fontWeight: '700',
    letterSpacing: 0.4,
    fontSize: 11,
    textTransform: 'uppercase',
  },
  brandTitle: {
    color: palette.text,
    fontSize: 21,
    fontWeight: '800',
    fontFamily: typography.display,
    letterSpacing: 0.2,
  },
  header: {
    marginBottom: 16,
  },
  headerCopy: {
    gap: 6,
  },
  headerSubtitle: {
    color: 'rgba(230,237,255,0.7)',
    fontSize: 13,
    lineHeight: 18,
    fontFamily: typography.body,
  },
  headerAction: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  headerActionText: {
    color: palette.text,
    fontWeight: '700',
    fontSize: 13,
    fontFamily: typography.body,
  },
  listContent: {
    paddingHorizontal: 0,
  },
  slideWrapper: {
    width: slideWidth,
    paddingHorizontal: 10,
  },
  card: {
    flex: 1,
    height: cardHeight,
    borderRadius: 28,
    padding: 20,
    justifyContent: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    overflow: 'hidden',
  },
  cardSheen: {
    position: 'absolute',
    top: -60,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  cardGlow: {
    position: 'absolute',
    bottom: -80,
    left: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(90,239,213,0.08)',
  },
  iconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(74, 140, 255, 0.16)',
    color: palette.success,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    fontWeight: '700',
  },
  badgePill: {
    marginTop: 14,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 18,
  },
  badgePillText: {
    fontWeight: '700',
  },
  title: {
    color: palette.text,
    fontSize: 27,
    fontWeight: '800',
    marginBottom: 8,
    fontFamily: typography.display,
  },
  subtitle: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: typography.body,
  },
  previewShell: {
    height: previewHeight,
    borderRadius: 24,
    marginBottom: 16,
    padding: 13,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    overflow: 'hidden',
  },
  previewGlassTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '48%',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  previewGlassBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '52%',
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  previewGlow: {
    position: 'absolute',
    top: -16,
    right: -6,
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  previewOrbLeft: {
    position: 'absolute',
    bottom: -34,
    left: -26,
    width: 116,
    height: 116,
    borderRadius: 58,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  previewOrbRight: {
    position: 'absolute',
    top: 56,
    right: -30,
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  previewStroke: {
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
    bottom: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  liquidHighlight: {
    position: 'absolute',
    top: 12,
    left: 18,
    width: 92,
    height: 18,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  syncHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  syncBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  syncBadgeText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: '700',
    fontFamily: typography.body,
  },
  syncCounter: {
    color: palette.muted,
    fontSize: 12,
    fontFamily: typography.mono,
  },
  inboxCard: {
    borderRadius: 18,
    backgroundColor: 'rgba(8,12,26,0.36)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    padding: 12,
    gap: 10,
  },
  inboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  avatarDot: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inboxMeta: {
    flex: 1,
    gap: 5,
  },
  inboxLine: {
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  progressTrack: {
    marginTop: 10,
    height: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  syncFooter: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  syncFooterText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: '700',
  },
  syncFooterSubtext: {
    color: palette.muted,
    fontSize: 11,
  },
  applicationsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  applicationsHeaderTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: '800',
    fontFamily: typography.display,
  },
  applicationsPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  applicationsPillText: {
    color: palette.text,
    fontSize: 11,
    fontWeight: '700',
  },
  appList: {
    gap: 10,
  },
  appCard: {
    borderRadius: 16,
    padding: 11,
    backgroundColor: 'rgba(8,12,26,0.34)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  appCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  appTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: '800',
    fontFamily: typography.display,
    flex: 1,
  },
  appMeta: {
    color: palette.muted,
    fontSize: 12,
    marginTop: 4,
    fontFamily: typography.body,
  },
  statusChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  statusChipText: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  miniChipRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 9,
  },
  miniChip: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.13)',
  },
  miniChipText: {
    color: palette.text,
    fontSize: 10,
    fontWeight: '700',
  },
  pipelineHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  pipelineTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: '800',
    fontFamily: typography.display,
  },
  board: {
    flexDirection: 'row',
    gap: 10,
    flex: 1,
  },
  column: {
    flex: 1,
    borderRadius: 18,
    padding: 9,
    backgroundColor: 'rgba(8,12,26,0.28)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    gap: 8,
  },
  columnLabel: {
    color: palette.text,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  pipelineCard: {
    borderRadius: 14,
    padding: 9,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    gap: 5,
  },
  pipelineCardTitle: {
    color: palette.text,
    fontSize: 12,
    fontWeight: '800',
  },
  pipelineCardMeta: {
    color: palette.muted,
    fontSize: 10,
  },
  insightsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  insightsTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: '800',
    fontFamily: typography.display,
  },
  insightsSubtle: {
    color: palette.muted,
    fontSize: 11,
  },
  statRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  statCard: {
    flex: 1,
    borderRadius: 16,
    padding: 12,
    backgroundColor: 'rgba(8,12,26,0.32)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    gap: 6,
  },
  statLabel: {
    color: palette.muted,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  statValue: {
    color: palette.text,
    fontSize: 24,
    fontWeight: '800',
    fontFamily: typography.display,
  },
  statTrend: {
    fontSize: 11,
    fontWeight: '700',
  },
  chartShell: {
    borderRadius: 18,
    padding: 14,
    backgroundColor: 'rgba(8,12,26,0.34)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    gap: 12,
  },
  chartBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: 82,
    gap: 8,
  },
  chartBarTrack: {
    flex: 1,
    height: '100%',
    justifyContent: 'flex-end',
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.07)',
    overflow: 'hidden',
  },
  chartBarFill: {
    width: '100%',
    borderRadius: 999,
  },
  insightCallout: {
    borderRadius: 14,
    padding: 12,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  insightCalloutTitle: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
  },
  insightCalloutBody: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginTop: 20,
    marginBottom: 16,
  },
  dot: {
    height: 12,
    borderRadius: 8,
  },
  primaryButton: {
    backgroundColor: palette.primary,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    shadowColor: palette.primary,
    shadowOpacity: 0.25,
    shadowRadius: 12,
  },
  primaryButtonText: {
    color: palette.text,
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: 0.3,
    fontFamily: typography.display,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    paddingVertical: 12,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  secondaryButtonText: {
    color: palette.text,
    fontWeight: '700',
    fontSize: 13,
    fontFamily: typography.body,
  },
  tertiaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    marginBottom: 6,
  },
  tertiaryButtonText: {
    color: 'rgba(230,237,255,0.78)',
    fontWeight: '700',
    fontSize: 13,
    fontFamily: typography.body,
  },
  mainCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 24,
    backgroundColor: palette.card,
    padding: 24,
    borderWidth: 1,
    borderColor: palette.overlayBorder,
    alignSelf: 'center',
    marginTop: 80,
  },
});
