// Constants for Gmail sync - ATS platforms, domains, and configuration

// ATS platform words (used to filter out platform names from company extraction)
export const ATS_WORDS = [
    'workday',
    'myworkday',
    'myworkdayjobs',
    'workdayjobs',
    'ashby',
    'ashbyhq',
    'icims',
    'greenhouse',
    'grnh',
    'lever',
    'smartrecruiters',
    'taleo',
    'successfactors',
    'workable',
    'jobvite',
    'bamboohr',
    'recruitee',
    'breezy',
    'rippling',
    'applytojob',
    'interviewing',
    'greenhouse-mail',
    'smartrecruiters',
    'glassdoor',
    'jointaro',
    'gmail',
    'mail',
    'talent',
    'recruiting',
    'careers',
    'jobs',
    'candidate portal',
    'candidate login',
    'job requisition',
    // Additional ATS platforms
    'wellfound',
    'angellist',
    'hired',
    'triplebyte',
    'vettery',
    'underdog',
    'otta',
    'cord',
    'ycombinator',
    'workatastartup',
    'angel',
    // Removed legitimate companies: 'notion', 'lattice', 'gusto', 'remote'
    'remote',
    'oyster',
    'factorial',
    'personio',
    'sage',
    'zenefits',
    'namely',
    'paylocity',
    'paycom',
    'ceridian',
    'ultipro',
    'kronos',
    'ukg',
    'adp',
    'paychex',
];

// ATS domains for email sender detection
export const ATS_DOMAINS = [
    'workday.com',
    'myworkday.com',
    'myworkdayjobs.com',
    'ashbyhq.com',
    'icims.com',
    'greenhouse.io',
    'grnh.se',
    'jobs.lever.co',
    'hire.lever.co',
    'smartrecruiters.com',
    'taleo.net',
    'successfactors.com',
    'workable.com',
    'jobvite.com',
    'bamboohr.com',
    'recruitee.com',
    'breezy.hr',
    // Additional ATS domains
    'wellfound.com',
    'angel.co',
    'hired.com',
    'triplebyte.com',
    'vettery.com',
    'underdog.io',
    'otta.com',
    'cord.co',
    'workatastartup.com',
    'eightfold.ai',
    'phenom.com',
    'beamery.com',
    'gem.com',
    'hiretual.com',
    'seekout.com',
    'entelo.com',
    'findem.ai',
    'paradox.ai',
    'xor.ai',
    'mya.com',
    'olivia.paradox.ai',
    'humanly.io',
    'fetcher.ai',
    'hireez.com',
    'sourcinghub.io',
    'textrecruit.com',
    'grayscale.io',
    'fountain.com',
    'retool.com',
    'apply.workable.com',
    'jobs.ashbyhq.com',
    'boards.eu.greenhouse.io',
    'app.dover.io',
    'dover.io',
    'hirebridge.com',
    'jazz.co',
    'jazzhr.com',
    'clearcompany.com',
    'paycor.com',
    'ultipro.com',
    'ukg.com',
    'cornerstoneondemand.com',
    'dayforce.com',
];

// Preferred portal domains for extraction
export const PREFERRED_PORTAL_DOMAINS = [
    'myworkdayjobs.com',
    'myworkday.com',
    'workday.com',
    'greenhouse.io',
    'job-boards.greenhouse.io',
    'boards.greenhouse.io',
    'grnh.se',
    'ashbyhq.com',
    'lever.co',
    'smartrecruiters.com',
    'icims.com',
    'taleo.net',
    'successfactors.com',
    'workable.com',
    'jobvite.com',
    'bamboohr.com',
    'recruitee.com',
    'breezy.hr',
    // Additional platforms
    'dover.io',
    'gem.com',
    'wellfound.com',
    'angel.co',
    'hired.com',
    'otta.com',
    'underdog.io',
    'workatastartup.com',
    'jazzhr.com',
    'jazz.co',
    'clearcompany.com',
    'hirebridge.com',
    'paylocity.com',
    'paycor.com',
    'ceridian.com',
    'dayforce.com',
    'eightfold.ai',
    'phenom.com',
    'beamery.com',
    'fountain.com',
    'rippling.com',
];

// Status priority for merging multiple status signals
export const STATUS_PRIORITY: Record<string, number> = {
    Offer: 5,
    Rejected: 4,
    Interview: 3,
    Assessment: 2,
    Applied: 1,
    Other: 0,
};

// Batch processing configuration
export const BATCH_SIZE = 15;
export const MAX_CONCURRENT_BATCHES = 4;

// Sync timing configuration
export const TIME_BUDGET_MS = 110_000;
export const LLM_MIN_TIME_REMAINING_MS = 15_000;
export const PHASE1_LOOKBACK_DAYS = 60;
export const DEEP_SYNC_MAX_MESSAGES_PER_RUN = 300;
export const DEEP_SYNC_TOTAL_LIMIT = DEEP_SYNC_MAX_MESSAGES_PER_RUN * 20;

// Company extraction minimum score threshold
export const COMPANY_MIN_SCORE = 2;

// HTTP response headers
export const JSON_HEADERS = {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
};
