type MockSeed = {
  subject: string;
  from: string;
  snippet: string;
  body: string;
  daysAgo: number;
  thread: string;
};

const MOCK_SEED: MockSeed[] = [
  {
    subject: 'Application received — Product Designer',
    from: 'Greenhouse <no-reply@greenhouse.io>',
    snippet: 'Thanks for applying to Figma. We received your application.',
    body: `Hi there,\n\nThanks for applying to Figma for the Product Designer role. Your application has been received.\n\nFigma Recruiting`,
    daysAgo: 2,
    thread: 'figma-1',
  },
  {
    subject: 'Your application to Notion',
    from: 'Notion Recruiting <recruiting@notion.so>',
    snippet: 'We received your application for Backend Engineer.',
    body: `Thanks for applying to Notion for the Backend Engineer role. We'll review your application and follow up soon.\n\nNotion`,
    daysAgo: 5,
    thread: 'notion-1',
  },
  {
    subject: 'Next steps: Phone screen at Stripe',
    from: 'Stripe Recruiting <recruiting@stripe.com>',
    snippet: 'We would like to schedule a 30-minute phone screen.',
    body: `Hi,\n\nWe reviewed your application for Software Engineer at Stripe and would like to schedule a 30-minute phone screen.\n\nPlease share your availability.\n\nThanks,\nStripe Recruiting`,
    daysAgo: 7,
    thread: 'stripe-1',
  },
  {
    subject: 'Interview scheduled — Dropbox',
    from: 'Dropbox <interviews@dropbox.com>',
    snippet: 'Your interview is confirmed for Thursday at 2:00 PM PT.',
    body: `Great news! Your interview for iOS Engineer at Dropbox is scheduled for Thursday at 2:00 PM PT.\nMeeting link: https://zoom.us/j/123456789\n\nDropbox`,
    daysAgo: 8,
    thread: 'dropbox-1',
  },
  {
    subject: 'Assessment invitation — Canva',
    from: 'Canva Talent <talent@canva.com>',
    snippet: 'Please complete the take-home assessment by Friday.',
    body: `Hi there,\n\nPlease complete the take-home assessment for the Frontend Engineer role by Friday. Link: https://codesignal.com/demo\n\nCanva`,
    daysAgo: 10,
    thread: 'canva-1',
  },
  {
    subject: 'Update on your application',
    from: 'Ashby <no-reply@ashbyhq.com>',
    snippet: 'Thank you for your interest in Lattice.',
    body: `Thank you for your interest in Lattice. We have decided to move forward with other candidates for the Growth Marketing role.\n\nLattice Recruiting`,
    daysAgo: 12,
    thread: 'lattice-1',
  },
  {
    subject: 'Offer — Senior Engineer',
    from: 'Gusto <talent@gusto.com>',
    snippet: 'We are excited to extend you an offer.',
    body: `Congratulations! Gusto would like to extend you an offer for the Senior Engineer role.\n\nPlease review the offer letter in the attached portal.\n\nGusto`,
    daysAgo: 13,
    thread: 'gusto-1',
  },
  {
    subject: 'Application confirmation',
    from: 'Workday <workday@company.workday.com>',
    snippet: 'Your application to Adobe has been submitted.',
    body: `This is to confirm your application to Adobe for the Data Scientist role.\n\nThank you,\nAdobe Careers`,
    daysAgo: 14,
    thread: 'adobe-1',
  },
  {
    subject: 'Interview request: Machine Learning Engineer',
    from: 'OpenAI Recruiting <recruiting@openai.com>',
    snippet: 'We’d like to schedule a technical interview.',
    body: `Hi,\n\nWe’d like to schedule a technical interview for the Machine Learning Engineer role. Please share your availability.\n\nOpenAI`,
    daysAgo: 15,
    thread: 'openai-1',
  },
  {
    subject: 'Re: Interview availability',
    from: 'OpenAI Recruiting <recruiting@openai.com>',
    snippet: 'Thanks for your availability — confirming Tuesday 11:00 AM PT.',
    body: `Thanks! Confirming your interview on Tuesday at 11:00 AM PT.\n\nOpenAI Recruiting`,
    daysAgo: 14,
    thread: 'openai-1',
  },
  {
    subject: 'Your CodeSignal assessment',
    from: 'CodeSignal <noreply@codesignal.com>',
    snippet: 'You’ve been invited to complete an assessment for Atlassian.',
    body: `You’ve been invited to complete a CodeSignal assessment for Atlassian (Frontend Engineer).\nComplete by end of week: https://codesignal.com/test/xyz\n`,
    daysAgo: 16,
    thread: 'atlassian-1',
  },
  {
    subject: 'Application received — Product Manager',
    from: 'Lever <no-reply@lever.co>',
    snippet: 'Thanks for applying to Airtable.',
    body: `Thanks for applying to Airtable for the Product Manager role. We’ll be in touch.\n\nAirtable`,
    daysAgo: 18,
    thread: 'airtable-1',
  },
  {
    subject: 'Interview invite — Coinbase',
    from: 'Coinbase Talent <talent@coinbase.com>',
    snippet: 'We’d like to schedule a video interview.',
    body: `Hi,\n\nWe’d like to schedule a video interview for the Product Designer role at Coinbase. Please share times.\n\nCoinbase`,
    daysAgo: 20,
    thread: 'coinbase-1',
  },
  {
    subject: 'Application status update',
    from: 'SmartRecruiters <no-reply@smartrecruiters.com>',
    snippet: 'Thank you for applying to Spotify.',
    body: `Thank you for applying to Spotify for the Backend Engineer role.\nWe are moving forward with other candidates.\n\nSpotify`,
    daysAgo: 21,
    thread: 'spotify-1',
  },
  {
    subject: 'Your interview with Shopify',
    from: 'Shopify <interviews@shopify.com>',
    snippet: 'Interview scheduled for Monday 9:30 AM ET.',
    body: `Your interview for the Data Engineer role is scheduled for Monday at 9:30 AM ET.\nMeeting link: https://meet.google.com/abc-defg-hij\n`,
    daysAgo: 22,
    thread: 'shopify-1',
  },
  {
    subject: 'Thanks for applying — QA Engineer',
    from: 'BambooHR <no-reply@bamboohr.com>',
    snippet: 'We received your application to Asana.',
    body: `Hi,\n\nWe received your application to Asana for the QA Engineer role. We’ll review and follow up.\n\nAsana`,
    daysAgo: 24,
    thread: 'asana-1',
  },
  {
    subject: 'Hiring team update',
    from: 'LinkedIn Talent <talent@linkedin.com>',
    snippet: 'We’re moving forward with other candidates.',
    body: `Thanks for your interest in LinkedIn. We’re moving forward with other candidates for the iOS Engineer role.`,
    daysAgo: 25,
    thread: 'linkedin-1',
  },
  {
    subject: 'Assessment request — Data Analyst',
    from: 'HackerRank <noreply@hackerrank.com>',
    snippet: 'You have been invited to complete a HackerRank test.',
    body: `You have been invited to complete a HackerRank test for the Data Analyst role at Square.\nPlease complete within 5 days.`,
    daysAgo: 26,
    thread: 'square-1',
  },
  {
    subject: 'Application received — Security Engineer',
    from: 'Greenhouse <no-reply@greenhouse.io>',
    snippet: 'Thanks for applying to Cloudflare.',
    body: `Thanks for applying to Cloudflare for the Security Engineer role.\n\nCloudflare Recruiting`,
    daysAgo: 27,
    thread: 'cloudflare-1',
  },
  {
    subject: 'Interview scheduling: Data Science',
    from: 'Databricks Recruiting <recruiting@databricks.com>',
    snippet: 'Please select a time for your interview.',
    body: `Please select a time for your Data Scientist interview at Databricks.\nScheduling link: https://calendly.com/databricks/interview`,
    daysAgo: 28,
    thread: 'databricks-1',
  },
  {
    subject: 'Offer extended — Frontend Engineer',
    from: 'Notion Recruiting <recruiting@notion.so>',
    snippet: 'We are excited to extend an offer.',
    body: `We are excited to extend an offer for the Frontend Engineer role at Notion.\n\nNotion Recruiting`,
    daysAgo: 29,
    thread: 'notion-2',
  },
  {
    subject: 'Thanks for applying — Customer Success',
    from: 'Workable <no-reply@workable.com>',
    snippet: 'Thanks for applying to HubSpot.',
    body: `Thanks for applying to HubSpot for the Customer Success Manager role. We’ll be in touch.`,
    daysAgo: 30,
    thread: 'hubspot-1',
  },
  {
    subject: 'Interview follow-up — Marketing Manager',
    from: 'Gusto <talent@gusto.com>',
    snippet: 'We would like to schedule a follow-up interview.',
    body: `We’d like to schedule a follow-up interview for the Marketing Manager role at Gusto.`,
    daysAgo: 31,
    thread: 'gusto-2',
  },
];

export function buildMockMessages(userId: string) {
  const now = Date.now();
  return MOCK_SEED.map((item, index) => ({
    user_id: userId,
    gmail_message_id: `mock-${userId}-${index + 1}`,
    gmail_thread_id: `mock-thread-${userId}-${item.thread}`,
    internet_message_id: `<mock-${userId}-${index + 1}@basafy.app>`,
    subject: item.subject,
    from_address: item.from,
    snippet: item.snippet,
    body_text: item.body,
    received_at: new Date(now - item.daysAgo * 24 * 60 * 60 * 1000).toISOString(),
  }));
}
